### ISSUE TITLE
Logo.png sometimes doesn't load in server - publications.js (package name - ostrio:files)

### ISSUE THREAD

**Issue by teresalazar13** [jeKnowledge/the-grad-list-v2#1]

**Comment by mikeevmm** [comment]
Where is the code for the adding of the logo located?

**Comment by jbernardo95** [comment]
@teresalazar13 Where and how are you handling image uploading ?

**Comment by teresalazar13** [comment]
I'm using a package called ostrie:files. In this commit you can see how I'm handling image uploading: https://github.com/jeKnowledge/the-grad-list-v2/commit/23728826d3231193c911987e3e7292c4e673e8ca. 
However, the default profile picture(logo.png), isn't being loaded in publications.js and when a user signs up a Meteor method called defaultPicture is called and his default profile picture isn't being displayed (even though in the database he has an image field with the correct id of the logo).

**Comment by jbernardo95** [comment]
@teresalazar13 Is image uploading working on the heroku instance ?

**Comment by teresalazar13** [comment]
yes @jbernardo95

**Comment by jbernardo95** [comment]
@teresalazar13 And they show up with no problem ?

**Comment by teresalazar13** [comment]
yes, its just the default profile picture(logo.png) and facebook profile pictures that are not being loaded in Server/publication.js ->meteor.startup function and server/MeteorMethods.js -> loginFacebook and defaultPicture functions. @jbernardo95

**Comment by jbernardo95** [comment]
@teresalazar13 seems to be working now, can you please check ?

**Comment by teresalazar13** [comment]
@jbernardo95 yes, it is working! thanks :)

**Comment by jbernardo95** [comment]
I'll close it then :)
