### ISSUE TITLE
Use ENV vars to store api credentials

### ISSUE THREAD

**Issue by jbernardo95** [jeKnowledge/the-grad-list-v2#13]
In this [file](https://github.com/jeKnowledge/the-grad-list-v2/blob/master/server/publications.js#L70) for example the fb api credentials _should_ not be in the source control.

Imagine if this credentials gave access to our bank account, would it be a good thing if everyone knew out bank account credentials ?

This package fixes our problem: https://github.com/okgrow/meteor-dotenv

**Comment by pedrocaseiro** [comment]
@teresalazar13 we need to address this asap!

**Comment by teresalazar13** [comment]
fixed
