### ISSUE TITLE
Facebook login

### ISSUE THREAD

**Issue by teresalazar13** [jeKnowledge/the-grad-list-v2#17]
With Facebook v2.4 API I'm not able to update the user's fields with the facebook's name and profile picture.

**Comment by pedrocaseiro** [comment]
this? https://developers.facebook.com/docs/graph-api/reference/v2.4/user/picture

**Comment by teresalazar13** [comment]
I don't think so. I think it has to do with the method "loginFacebook" not doing anything in Client/templates/authentication.js

**Comment by teresalazar13** [comment]
fixed
