### ISSUE TITLE
Sexy hover animation on "Users that you can follow"

### ISSUE THREAD

**Issue by goamaral** [jeKnowledge/the-grad-list-v2#25]
![imp 1](https://cloud.githubusercontent.com/assets/3640909/19282878/db157e22-8fe7-11e6-8c09-32d5d3dd8c97.JPG)

**Comment by goamaral** [comment]
This aint really a feature doctor @pedrocaseiro. I think the "improvement" tag would be more suitable.

**Comment by teresalazar13** [comment]
Fixed
