### ISSUE TITLE
jeKnowledge logo has a weird font

### ISSUE THREAD

**Issue by davidgomes** [jeKnowledge/the-grad-list-v2#32]
<img width="598" alt="screen shot 2016-10-11 at 6 50 27 pm" src="https://cloud.githubusercontent.com/assets/741621/19283806/4049eda2-8feb-11e6-8dcb-98283068dd40.png">

**Comment by teresalazar13** [comment]
fixed

**Comment by teresalazar13** [comment]
@mariamargarida fixed
