### ISSUE TITLE
Fix share buttons

### ISSUE THREAD

**Issue by teresalazar13** [jeKnowledge/the-grad-list-v2#4]

**Comment by jbernardo95** [comment]
@teresalazar13 More details please ?

**Comment by teresalazar13** [comment]
In client/templates/posts post_item.js, I want to display only facebook, twitter and google icons

**Comment by jbernardo95** [comment]
@teresalazar13 It's on me 🙂

**Comment by teresalazar13** [comment]
@jbernardo95 Thaanks!! :)

**Comment by jbernardo95** [comment]
@teresalazar13 You want to remove the Pintrest icon, am I right ?

**Comment by teresalazar13** [comment]
yes @jbernardo95 !

**Comment by jbernardo95** [comment]
@teresalazar13 review please ^

**Comment by jbernardo95** [comment]
Merge and close
