### ISSUE TITLE
#GetBinLadenBack

### ISSUE THREAD

**Issue by goamaral** [jeKnowledge/the-grad-list-v2#42]
Find Bin Laden picture
![is](https://cloud.githubusercontent.com/assets/3640909/19533435/ab198a14-9637-11e6-93b5-da57b1dfb0d5.png)

He looks like this
![issue](https://cloud.githubusercontent.com/assets/3640909/19533510/f5e3e026-9637-11e6-84a5-55abab13b1c4.jpg)

Please find him

**Comment by Cotemero** [comment]
If possible, steps to reproduce.

**Comment by Cotemero** [comment]
Someone cleared CDN. Who was it?

**Comment by miguelantoniosantos** [comment]
We need to change to another CDN, Heroku CDN is for caching not static files.

**Comment by miguelantoniosantos** [comment]
Waiting for pull request confirmation. Needs changes before production.
