### ISSUE TITLE
A user can fork the same post several times leading to copies of the same post on the user's page

### ISSUE THREAD

**Issue by jbernardo95** [jeKnowledge/the-grad-list-v2#58]

**Comment by teresalazar13** [comment]
After a user forks a post, a notification is already appearing saying "Fork success". Do you think that is enough or is it best if after a user forks a post that the page is refreshed? Also, it is possible that the user will want to fork the post again, so blocking the fork button to him might not be the best option. What do you think? @jbernardo95
