### ISSUE TITLE
Improve post action buttons titles

### ISSUE THREAD

**Issue by jbernardo95** [jeKnowledge/the-grad-list-v2#60]
<img width="651" alt="screen shot 2016-12-12 at 18 23 09" src="https://cloud.githubusercontent.com/assets/6342528/21111153/22df8c08-c098-11e6-8ea2-368d727cdb9e.png">

`Remove` -> `Delete`
`Complete` -> `Mark as complete` or `Completed`

Maybe ??? ^

**Comment by teresalazar13** [comment]
fixed
