### ISSUE TITLE
Complete button does not complete a post

### ISSUE THREAD

**Issue by jbernardo95** [jeKnowledge/the-grad-list-v2#61]
After clicking the `Complete` button on a post I am redirected to a `Complete` page telling me that the post is complete when in fact is not.

Only after clicking the `Submit` button it becomes complete.

Maybe clicking the complete button should complete the post and adding a picture should be optional ???

<img width="1423" alt="screen shot 2016-12-12 at 18 26 00" src="https://cloud.githubusercontent.com/assets/6342528/21111340/f4eaf0c0-c098-11e6-936f-d570f23036ef.png">

**Comment by teresalazar13** [comment]
fixed
